addons:
  apt:
    packages:
      - aspell
language: perl
perl:
  - "5.8.1"
  - "5.8.1-thr"
  - "5.8.2"
  - "5.8.2-thr"
  - "5.8.3"
  - "5.8.3-thr"
  - "5.8.4"
  - "5.8.4-thr"
  - "5.8"
  - "5.10"
  - "5.12"
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.20"
  - "5.22"
  - "5.24"
  - "5.26"
  - blead       # builds perl from git
  - dev         # latest point release
matrix:
  include:
    - perl: 5.18
      env: COVERAGE=1
sudo: false
before_install:
  - eval $(curl https://travis-perl.github.io/init) --auto
branches:
  except:
    - /^wip\//
    - /^blocked/
notifications:
  email: false
  irc:
    channels:
      - "irc.perl.org#moo-smoke"
    template:
      - "%{branch}#%{build_number} by %{author}: %{message} (%{build_url})"
    on_success: change
    on_failure: always
    skip_join: true
